### ISSUE TITLE
AppsFlyer for android depends on old libraries

### ISSUE THREAD

**Issue by ybereza** [AppsFlyerSDK/AppsFlyerAndroidSDK#5]
AppsFlyer 4.10.0

rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.GcmInstanceIdListener>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceIDListenerService;

InstanceIDListenerService - is a part of Google Cloud Messaging, and this service is currently deprecated. Pls. remove this dependency.

Rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.FirebaseInstanceIdListener>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceIdService;

FirebaseInstanceIdService class was removed from Firebase library. You need to use FirebaseMessagingService instead of old one.

https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService

**Comment by BenjaminAF** [comment]
@ybereza FirebaseMessagingServiceListener (that makes use of FirebaseMessagingService) is already included in v4.10.0
FirebaseInstanceIdService is still available since the newer FirebaseMessagingService is available starting `firebase:messaging:17.1.0`

We will remove all leftover GCM references in the upcoming release .

**Comment by ybereza** [comment]
But there is already com.google.firebase:firebase-messaging:19.0.1, and we are using messaging:18.0.0 in our application

**Comment by BenjaminAF** [comment]
@ybereza right.
Still, what is the issue? you can make use of the newer FirebaseMessagingServiceListener (that replaces the deprecated FirebaseInstanceIdServiceListener) in our SDK - this listener uses the new FirebaseMessagingService.

The older FirebaseInstanceIdServiceListener is still there (though deprecated) for users who still use older versions of Firebase.
What am I missing here?

**Comment by ybereza** [comment]
We have updated our project to com.google.firebase:firebase-messaging:18.0.0 and there is no FirebaseInstanceIdService in this version. So we have log messages with stack trace java.lang.NoClassDefFoundError in new build. Our automated tests scans logcat after application start, detects this error, treats it as an exception and fails :(

**Comment by BenjaminAF** [comment]
@ybereza thanks for the clarification - we will eventually remove those classes from our SDK, but for now we still wish to keep them in order to allow compatibility with older versions of Firebase (We did deprecate them, but we cannot remove them so quickly).

In addition, all those classes are accessed by reflection - there is no direct invocation of FirebaseInstanceIdService. So there is no real risk in keeping the references.

**Comment by jasongaare** [comment]
@BenjaminAF do you know when you will remove this? Cannot build our app due to this issue. Or is there a work around to avoid the error I receive? The same error reference in #7

**Comment by Fudds** [comment]
I am running into this same problem, even on the newest Appsflyer plugin 4.22.1

I don't even have Firebase in my project

**Comment by AfzalivE** [comment]
AppsFlyer 5.3.0 hasn't had this updated either!

**Comment by af-fess** [comment]
@Fudds `4.22.1` is related to old Unity plugin. Did you try https://github.com/AppsFlyerSDK/appsflyer-unity-plugin?
